#!/bin/bash
sudo docker ps -a | grep final-python
EXITCODE=$?
if [ "$EXITCODE" -ne "0" ]; then
    #this is the catch part
    echo "uh oh"
    exit 0
else
    sudo docker stop final-python
    sudo docker rm final-python

fi
